-- CREATING FOREIGN KEYS
ALTER TABLE post ADD FOREIGN KEY (author_id) REFERENCES person(id);

-- CREATING TABLES
CREATE TABLE IF NOT EXISTS post_like (
id INTEGER AUTO_INCREMENT,
time DATETIME,
person_id INTEGER NOT NULL,
post_id INTEGER NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post_file (
id INTEGER AUTO_INCREMENT,
post_id INTEGER NOT NULL,
name VARCHAR(50),
path VARCHAR(50),
PRIMARY KEY (id)
);

-- CREATING FOREIGN KEYS
ALTER TABLE post_like ADD FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE post_like ADD FOREIGN KEY (post_id) REFERENCES post(id);
ALTER TABLE post_file ADD FOREIGN KEY (post_id) REFERENCES post(id);